### ISSUE TITLE
Idear o nome do projeto

### ISSUE THREAD

**Issue by jtomaz99** [jtomaz99/4R#10]
Criação do nome da aplicação.

**Comment by vitorlima-vl** [comment]
Nome decidido: '4R' (Replanejar, Reutilizar, Recursos e Reduzir).

Justificativa: a aplicação tem como objetivo **replanejar** o fluxo atual de descarte e compra de **recursos** para que a própria instituição possa **reutilizá-los** a fim de **reduzir** gastos. As 4 palavras chaves, todas começando com R, representam bem essa proposta.
