### ISSUE TITLE
Lista dos membros

### ISSUE THREAD

**Issue by vinicius3w** [jtomaz99/4R#9]
Por favor, coloca pelo menos o sobrenome dos membros e o login de cada um deles. por exemplo: Vinicius Garcia (vcg)

Indica também que está como líder do time

**Comment by jtomaz99** [comment]
Vou te enviar por email essas informações.

**Comment by vinicius3w** [comment]
ok


--
*Vinicius Cardoso Garcia*
[www: viniciusgarcia.me]-[arxiv: http://arxiv.org/a/garcia_v_1]-[twitter:
@vinicius3w <http://www.twitter.com/vinicius3w>]


*Wyrd biõ fui arccd.*

**Comment by jtomaz99** [comment]
Email Enviado!
